services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: talentai_backend
    environment:
      # Database Configuration - External PostgreSQL
      POSTGRES_SERVER: ${POSTGRES_SERVER:-localhost}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-talentai_db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      ENVIRONMENT: ${ENVIRONMENT:-production}
      # Application Port
      PORT: ${PORT:-8000}
    volumes:
      - ./data:/app/data:ro
      - models_data:/app/models
      - logs_data:/app/logs
      - ./ml_models:/app/ml_models:ro
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    networks:
      - dokploy-network
    restart: unless-stopped
    labels:
      - traefik.docker.network=dokploy-network
      - traefik.enable=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-8000}/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s


# Volumes
volumes:
  models_data:
    driver: local
    name: talentai_models_data_production
  
  logs_data:
    driver: local
    name: talentai_logs_data_production

networks:
  dokploy-network:
    external: true
