services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: talentai_backend
    environment:
      # Database Configuration - External PostgreSQL
      POSTGRES_SERVER: ${POSTGRES_SERVER:-localhost}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-talentai_db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      ENVIRONMENT: ${ENVIRONMENT:-production}
      # Application Port
      PORT: ${PORT:-8000}
    expose:
      - '${PORT:-8000}'
    volumes:
      - ./data:/app/data:ro
      - models_data:/app/models
      - logs_data:/app/logs
      - ./ml_models:/app/ml_models:ro
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    networks:
      - dokploy-network
    restart: unless-stopped
    labels:
      - traefik.docker.network=dokploy-network
      - traefik.enable=true
      - traefik.http.routers.talentai-backend-fki80q-web.rule=Host(`talentai-backend-fki80q-22a901-144-126-135-34.traefik.me`)
      - traefik.http.routers.talentai-backend-fki80q-web.entrypoints=web
      - traefik.http.services.talentai-backend-fki80q-web.loadbalancer.server.port=${PORT:-8000}
      - traefik.http.routers.talentai-backend-fki80q-web.service=talentai-backend-fki80q-web
      - traefik.http.routers.talentai-backend-fki80q-web.middlewares=redirect-to-https@file
      - traefik.http.routers.talentai-backend-fki80q-websecure.rule=Host(`talentai-backend-fki80q-22a901-144-126-135-34.traefik.me`)
      - traefik.http.routers.talentai-backend-fki80q-websecure.entrypoints=websecure
      - traefik.http.services.talentai-backend-fki80q-websecure.loadbalancer.server.port=${PORT:-8000}
      - traefik.http.routers.talentai-backend-fki80q-websecure.service=talentai-backend-fki80q-websecure
      - traefik.http.routers.talentai-backend-fki80q-websecure.tls.certresolver=letsencrypt
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-8000}/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s


# Volumes
volumes:
  models_data:
    driver: local
    name: talentai_models_data_production
  
  logs_data:
    driver: local
    name: talentai_logs_data_production

networks:
  dokploy-network:
    external: true
