services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: talentai_backend
    environment:
      # Database Configuration - Only essential variables
      POSTGRES_SERVER: ${POSTGRES_SERVER:-localhost}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-talentai_db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      ENVIRONMENT: ${ENVIRONMENT:-production}
      # Application Port
      PORT: ${PORT:-8000}
    volumes:
      - ./data:/app/data:ro
      - ./models:/app/models
      - ./logs:/app/logs
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    restart: unless-stopped
    #labels:
    #  - "traefik.enable=true"
    #  - "traefik.http.routers.talentai-backend.rule=Host(`talentai-backend-fki80q-f6db00-144-126-135-34.traefik.me`)"
    #  - "traefik.http.routers.talentai-backend.entrypoints=web"
    #  - "traefik.http.services.talentai-backend.loadbalancer.server.port=8000"
    #  # HTTPS configuration (optional)
    #  - "traefik.http.routers.talentai-backend-secure.rule=Host(`talentai-backend-fki80q-f6db00-144-126-135-34.traefik.me`)"
    #  - "traefik.http.routers.talentai-backend-secure.entrypoints=websecure"
    #  - "traefik.http.routers.talentai-backend-secure.tls=true"
    #  - "traefik.http.routers.talentai-backend-secure.tls.certresolver=myresolver"
    #  - "traefik.http.services.talentai-backend-secure.loadbalancer.server.port=8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-8000}/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s