services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: talentai_backend
    environment:
      # Database Configuration - Only essential variables
      POSTGRES_SERVER: ${POSTGRES_SERVER:-localhost}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-talentai_db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      ENVIRONMENT: ${ENVIRONMENT:-development}
    volumes:
      - ./data:/app/data:ro
      - ./models:/app/models
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s